Scripts: Get rid of bash(isms)

diff --git a/script/bootstrap-lua b/script/bootstrap-lua
--- a/script/bootstrap-lua
+++ b/script/bootstrap-lua
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 # vim: set ts=4:
 #
 # This script ensures that lua interpreter and lua modules specified in Rocksfile are installed.
@@ -13,7 +13,7 @@
 #
 #   USE_SYSTEM_LUA : Set to 'yes' if you want to use system provided lua. Default is to install
 #                    lua locally in .env directory.
-set -e -o pipefail
+set -e
 
 DEFAULT_VERSION='luajit-2.1'
 HEREROCKS_URI='https://raw.githubusercontent.com/mpeterv/hererocks/0.20.0/hererocks.py'
@@ -22,7 +22,7 @@ show_path_warn=
 
 #======================  Functions  ======================#
 
-find-lua-exec() {
+find_lua_exec() {
 	local cmd; for cmd in lua luajit; do
 		if exists "$cmd"; then
 			command -v "$cmd"
@@ -32,27 +32,33 @@ find-lua-exec() {
 	return 1
 }
 
-check-lua-version() {
+check_lua_version() {
 	local luabin="$1"
-	local ver="$($luabin -v 2>&1 | cut -d' ' -f1-2 | tr '[A-Z] ' '[a-z]-' || '')"
+	local ver="$($luabin -v 2>&1 | cut -d' ' -f1-2 | tr '[A-Z] ' '[a-z]-' || echo '')"
 
-	if [ -n "$LUA_VERSION" ]; then
-		[[ "$ver" == "$LUA_VERSION"* ]]
+	if [ "$LUA_VERSION" ]; then
+		case "$ver" in
+			$LUA_VERSION*) return 0;;
+			*) return 1;;
+		esac
 	else
-		[[ "$ver" =~ ^lua-5.1|^luajit-2 ]]
+		case "$ver" in
+			lua-5.1* | luajit-2*) return 0;;
+			*) return 1;;
+		esac
 	fi
 }
 
-install-lua() {
-	local version=$1
+install_lua() {
+	local version=$(printf %s "$1" | tr - =)
 
 	curl -o "$TEMP_DIR/hererocks.py" "$HEREROCKS_URI"
-	python "$TEMP_DIR/hererocks.py" "$VENV_DIR" --luarocks=^ --${version/-/=}
+	python "$TEMP_DIR/hererocks.py" "$VENV_DIR" --luarocks=^ --$version
 }
 
-install-rock() {
+install_rock() {
 	local name="$1"
-	luarocks --mversion show "$name" &>/dev/null || luarocks install "$name"
+	luarocks --mversion show "$name" >/dev/null 2>&1 || luarocks install "$name"
 }
 
 
@@ -61,13 +67,13 @@ install-rock() {
 # Go to the project's root directory.
 cd "$(dirname "$0")/.."
 
-source script/common.sh
+. script/common.sh
 
 mkdir -p "$VENV_DIR" "$TEMP_DIR"
 
 if yesno "$USE_SYSTEM_LUA"; then
 
-	if ! check-lua-version "$(find-lua-exec)"; then
+	if ! check_lua_version "$(find_lua_exec)"; then
 		die "${LUA_VERSION:-lua 5.1 or luajit 2} is not installed and USE_SYSTEM_LUA=$USE_SYSTEM_LUA"
 
 	elif ! exists luarocks; then
@@ -75,18 +81,18 @@ if yesno "$USE_SYSTEM_LUA"; then
 	fi
 
 else
-	setup-path  # add .env/bin to PATH
+	setup_path  # add .env/bin to PATH
 
-	if ! check-lua-version "$VENV_DIR/bin/lua" || [ ! -x "$VENV_DIR/bin/luarocks" ]; then
+	if ! check_lua_version "$VENV_DIR/bin/lua" || [ ! -x "$VENV_DIR/bin/luarocks" ]; then
 		version="${LUA_VERSION:-$DEFAULT_VERSION}"
 
 		echo "==> Installing $version and luarocks into $VENV_DIR..."
-		install-lua $version
+		install_lua $version
 		echo ''
 	fi
 fi
 
 echo '==> Installing lua modules...'
 while read -r rockname; do
-	install-rock "$rockname" || die "Failed to install rock $rockname."
+	install_rock "$rockname" || die "Failed to install rock $rockname."
 done < Rocksfile
diff --git a/script/bootstrap-python b/script/bootstrap-python
--- a/script/bootstrap-python
+++ b/script/bootstrap-python
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 # vim: set ts=4:
 #
 # This script ensures that Python 3.3+ is available and installs modules
@@ -8,13 +8,13 @@
 #   PYTHON          : Python executable to use (default is python3 or python on PATH).
 #   USE_PYTHON_VENV : Set to 'no' if you don't want to initialize venv for modules.
 #
-set -e -o pipefail
+set -e
 
 : ${USE_PYTHON_VENV:=yes}
 
 #======================  Functions  ======================#
 
-find-python-exec() {
+find_python_exec() {
 	local cmd; for cmd in "$PYTHON" python3 python; do
 		if exists "$cmd"; then
 			PYTHON="$cmd"; return 0
@@ -23,12 +23,12 @@ find-python-exec() {
 	return 1
 }
 
-check-python-version() {
+check_python_version() {
 	$PYTHON -c 'import sys; exit(0) if sys.version_info >= (3, 3, 0) else exit(1)'
 }
 
-install-requirements() {
-	pip install $@ -r integration/requirements.txt
+install_requirements() {
+	pip install "$@" -r integration/requirements.txt
 }
 
 
@@ -37,16 +37,16 @@ install-requirements() {
 # Go to the project's root directory.
 cd "$(dirname "$0")/.."
 
-source script/common.sh
+. script/common.sh
 
 pyenv_dir="$VENV_DIR/python"
 
-find-python-exec || die 'Could not find python executable!'
-check-python-version || die "Python 3.3+ is required, but you have $($PYTHON -V 2>&1)!"
+find_python_exec || die 'Could not find python executable!'
+check_python_version || die "Python 3.3+ is required, but you have $($PYTHON -V 2>&1)!"
 
 if [ -d "$pyenv_dir" ]; then
 	# Just to be sure that all requirements are installed (should be already).
-	install-requirements -q
+	install_requirements -q
 
 elif yesno "$USE_PYTHON_VENV"; then
 	einfo '==> Initializing Python virtual environment and installing modules...'
@@ -54,12 +54,12 @@ elif yesno "$USE_PYTHON_VENV"; then
 	"$PYTHON" -m venv "$pyenv_dir"
 	export PATH="$pyenv_dir/bin:$PATH"
 
-	install-requirements
+	install_requirements
 
 	ln -sf "$pyenv_dir"/bin/* "$VENV_DIR"/bin/
 
 else
 	einfo '==> Installing Python modules...'
 
-	install-requirements
+	install_requirements
 fi
